CREATE DATABASE node_mysql_ts;

CREATE TABLE Person(
    id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(11) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIME,
    idRol VARCHAR(11)
)
CREATE TABLE Tasks(
    id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    task VARCHAR(200) NOT NULL,
    completed BOOLEAN NOT NULL,
    type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIME
   )

DESCRIBE Person